### ISSUE TITLE
Make point totals filter-aware

### ISSUE THREAD

**Issue by jofis** [luckyshot/agilescrumfortrello#17]
I'm trying to use this extension to manage sprints for a team. I frequently filter the board to show cards assigned to one team member. I would expect the point totals to reflect only the cards shown, but they continue to show the overall unfiltered totals. I find this non-intuitive. (FWIW, the Scrum for Trello extension does adjust the totals based on what the filter is showing.)

**Comment by oneezy** [comment]
This would be a great addon feature and could go well with the [PROJECTS] tagging #4
