### ISSUE TITLE
Tags not being colored when the word has an accent

### ISSUE THREAD

**Issue by Itisfilipe** [luckyshot/agilescrumfortrello#18]
words in portuguese like médico, automático does not getting colored when in inside brackets like [médico]. I think that's because of the accent...

**Comment by lPinchol** [comment]
It does not support accents. Checked.

**Comment by luckyshot** [comment]
This has been fixed now and accepts all (or most) accented characters:
`áãàâäéèẽêëíìĩîïóòõôöúùũûüçÁÃÀÂÄÉÈẼÊËÍÌĨÎÏÓÒÕÔÖÚÙŨÛÜÇ`
