### ISSUE TITLE
Agile Scrum for trello plug-in does not work

### ISSUE THREAD

**Issue by leonlee919** [luckyshot/agilescrumfortrello#22]
I have installed the plug-in but it is not working; I updated Chrome to the latest version, removed the plug-in and re-installed it. It is still not working. Is there anything necessary to activate it? I can see a small icon to the right of the URL field but it is in grey (not in coulour), does this mean that the plug-in is inactive? Thanks for your help.

**Comment by luckyshot** [comment]
Hi @leonlee919 
The plugin doesn't have any buttons or menus, it all is done by typing things.
Have you tried writing something in square brackets? Create a new card and type: `[hello]` then save it. The [hello] should convert to a colored rectangle. Same if you write `(0/1)` somewhere in the card, it should detect it as Story Points.

**Comment by leonlee919** [comment]
![capture d ecran 2016-10-06 a 1 28 26 pm](https://cloud.githubusercontent.com/assets/19396362/19150753/f0aece32-8bc8-11e6-9af8-7731f1ec4b1f.jpg)
Hi @luckyshot 
Thanks for your reply. I was talking about the small icon beside the address bar as in the attachment.
Also here is a screenshot on which you can see the tests I did but it didn't work the expected way. I asked two colleagues to intall the plug-in and test it; one of them has the tag working but none of us has the story point working. 
![capture d ecran 2016-10-06 a 1 30 51 pm](https://cloud.githubusercontent.com/assets/19396362/19150783/1f569b98-8bc9-11e6-8cf8-dccfe852a4b7.jpg)
We would love to be able to use this plug-in's different features.
Thanks a lot!

**Comment by luckyshot** [comment]
Can you tell me which version you have installed?
Check it out by opening the Chrome Developer Console when on Trello, you should see something like:
`Agile SCRUM for Trello boards v1.4.3 started`

**Comment by leonlee919** [comment]
It's v1.4.3
The version of Google Chrome is 53.0.2785.143 (64-bit)
![capture d ecran 2016-10-06 a 2 34 28 pm](https://cloud.githubusercontent.com/assets/19396362/19152398/1953bc90-8bd2-11e6-923e-d1f777e9d1ec.jpg)

**Comment by leonlee919** [comment]
@luckyshot hi, is there any update on the subject? Thanks.

**Comment by FreddyBenayas** [comment]
@leonlee919 Maybe you forgot to reload the page after adding the parenthesis and brackets etc... to the cards. The icon doesn't have to be active; it works for me although it isn't activated.

**Comment by luckyshot** [comment]
Yes, that icon just means the extension is installed, you can hide it by right-clicking and choosing _Hide in Chrome Menu_. 

Once installed, reloading the Trello page should do the job.
