### ISSUE TITLE
Checklist progress as Percentage of story points done in the card

### ISSUE THREAD

**Issue by luckyshot** [luckyshot/agilescrumfortrello#24]
We are using it in a game project, I just wanted to suggest a feature that would make the feature the
default for us: **consider the checklist progress (how many items are done from the checklist) as the percentage of story points done in the card, if the progress was not set manually.**

We already were using (#) in the card to set our story points, but changing the progress manually sounds like a hard sell to my team. I would love to see the progress bar for our cards with checklists without changing too much of our process.

--Rafael C.

_Received by email, thanks Rafael!_

**Comment by cymon1997** [comment]
Yeah, I think that should be great! Is there any progress about this feature?

**Comment by digitalade** [comment]
This sounds like a good idea, however I would view it a bit differently....

I would allow a user to assign story points to each checklist item and the sum of these becomes the card total.

However, as the 'back of the card' is loaded on an ad-hoc basis and the current code appears to utilise what is currently on the screen I feel a different approach to the coding of this would be needed?

Trello API maybe?

**Comment by Electrenator** [comment]
Just an idea but this could be done using the data in the `js-checkitems-badge-text` spans already on the page. Would love to see this in the extension
