### ISSUE TITLE
Tags only appear in 3 colors

### ISSUE THREAD

**Issue by larpo1** [luckyshot/agilescrumfortrello#28]
Hi - seems that no matter what i put in the tags brackets, the tags are only ever colored in three colors: light green darker green and gold. e.g. 

![image](https://user-images.githubusercontent.com/7364611/29435578-7d93c69e-839f-11e7-8cb1-599f1dfd9121.png)

**Comment by rudwolf** [comment]
I have created a pull request that solves this problem by adding the option to change the color tag using double underline on it's name, I don't know if that will help.

I am still waiting for the aproval to merge into the main branch;

#29

**Comment by luckyshot** [comment]
@rudwolf I've merged your request

**Comment by rudwolf** [comment]
@luckyshot I guess it will. But please, if possible, credit me for this change on the plugins page on chome extension store, and also, fix the explanation for it:

**FROM:**
Changelog
―――――――――――――――――――
★ 1.4.5
- Fixed Progress bar color not showing (thanks @danicg)
- Custom tag colors by adding "__red" or "__ff0" suffix

**TO:**
Changelog
―――――――――――――――――――
★ 1.4.5
- Fixed Progress bar color not showing (thanks @danicg)
- Custom tag colors by adding "__red" or "__#ff0" suffix (thanks @rudwolf)

**Comment by luckyshot** [comment]
Sure thing @rudwolf! 
I've credited you at the Chrome Store (may take a few hours to be published) and also in the README.md here at GitHub
Have a great weekend! 😊
