### ISSUE TITLE
Progress Bar change color to gray

### ISSUE THREAD

**Issue by MauZarazua** [luckyshot/agilescrumfortrello#30]
Hello, I used the plugin for many days, but today the “Progress Bars” changed the color to grey and you can`t see it. Anybody had this problem before ?

![captura de pantalla 2018-02-06 a las 18 40 51](https://user-images.githubusercontent.com/36213836/35892093-4d31e354-0b6d-11e8-98c1-be62cd314c1c.png)

**Comment by ekmpspete** [comment]
Looks like the background colour is now set on the body which messes up the logic on this line.
https://github.com/luckyshot/agilescrumfortrello/blob/66a54c6e98499c70cd6f998a35be9905eae6efe3/agilescrumfortrello.js#L134

**Comment by MauZarazua** [comment]
So, Anybody will fix it ? or How I can fix it ?
:(

**Comment by luckyshot** [comment]
Right now I'm overloaded with other work but will gladly approve any PRs

**Comment by danicg** [comment]
I sent a PR with the fix.

**Comment by MauZarazua** [comment]
Many thanks for the fix, but in the Chrome Web Store still appear the Versión: 1.4.3 with the error. How to update ?

**Comment by luckyshot** [comment]
Hi @MauZarazua ,

I submitted the new version yesterday but got [rejected for some reason](https://github.com/luckyshot/agilescrumfortrello/issues/32), Google told me to resubmit it again and should be available in a few hours.

**Comment by MauZarazua** [comment]
Now is working, 
Many thanks to all for your help...!
