### ISSUE TITLE
Plugin doesn't work on Firefox

### ISSUE THREAD

**Issue by abi-aryan** [luckyshot/agilescrumfortrello#36]
Hi,

I just installed the plugin from Mozilla Firefox Addon Store but unfortunately, it doesn't work.

![not work](https://user-images.githubusercontent.com/7281944/53259911-535d7800-36f6-11e9-90c1-114ee449cedc.PNG)

I also tried reloading and restarting Trello but to no aid. 

![capture](https://user-images.githubusercontent.com/7281944/53259925-5bb5b300-36f6-11e9-9f04-bab88177a581.PNG)

What am I doing wrong?

**Comment by Electrenator** [comment]
Hi, just want to mention that this plugin only works with specific things in the title of your cards. Specifically `(10)` and `(5/10)` with an input number of choice. This amongst a few other specific things found on [the instruction section of the `README.md`](https://github.com/luckyshot/agilescrumfortrello#instructions). These others are not that useful for me but may fit your use case :D
